import java.io.FileInputStream
import java.util.Properties

plugins {
    id("com.android.application")
    id("kotlin-android")
    // The Flutter Gradle Plugin must be applied after the Android and Kotlin Gradle plugins.
    id("dev.flutter.flutter-gradle-plugin")

    // 🔥 Firebase
    // - google-services: đọc google-services.json (1 cho mỗi flavor)
    // - crashlytics: upload mapping (R8) cho stack trace prod
    // PHASE 1: disabled — bật khi có google-services.json
    // id("com.google.gms.google-services")
    // id("com.google.firebase.crashlytics")
}

// ─── Read key.properties (release signing) ──────────────────────────
// Tạo `android/key.properties` (xem key.properties.example) — KHÔNG commit.
val keystoreProperties = Properties()
val keystorePropertiesFile = rootProject.file("key.properties")
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(FileInputStream(keystorePropertiesFile))
}

android {
    // ⚠️ namespace = package của Kotlin files (R class). KHÔNG đổi tuỳ tiện.
    // applicationId (cho user install) là `com.sportsbooking.mobile.*` per flavor — khác namespace OK.
    namespace = "com.example.flutter_base2"
    compileSdk = flutter.compileSdkVersion
    ndkVersion = flutter.ndkVersion

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
        // 🔧 Enable Java 8+ APIs (java.time, java.util.stream...) trên Android cũ.
        // Bắt buộc cho flutter_local_notifications + 1 số plugin khác.
        isCoreLibraryDesugaringEnabled = true
    }

    kotlinOptions {
        jvmTarget = JavaVersion.VERSION_17.toString()
    }

    defaultConfig {
        // ⚠️ flavorizr.gradle.kts override applicationId per flavor.
        applicationId = "com.sportsbooking.mobile"
        minSdk = flutter.minSdkVersion
        targetSdk = flutter.targetSdkVersion
        versionCode = flutter.versionCode
        versionName = flutter.versionName

        // Firebase + nhiều native plugins → enable multiDex cho an toàn.
        multiDexEnabled = true
    }

    // ─── Signing configs ────────────────────────────────────────────
    signingConfigs {
        create("release") {
            // Chỉ load nếu key.properties + keystore tồn tại — dev không có
            // keystore vẫn `flutter run --release` được (fallback debug ở buildTypes).
            val storeFileVal = keystoreProperties["storeFile"] as String?
            if (storeFileVal != null) {
                val keyFile = rootProject.file(storeFileVal)
                if (keyFile.exists()) {
                    storeFile = keyFile
                    keyAlias = keystoreProperties["keyAlias"] as String?
                    keyPassword = keystoreProperties["keyPassword"] as String?
                    storePassword = keystoreProperties["storePassword"] as String?
                } else {
                    println("⚠️ [Build] Release keystore '$storeFileVal' not found → fallback DEBUG signing.")
                }
            }
        }
    }

    buildTypes {
        debug {
            signingConfig = signingConfigs.getByName("debug")
        }
        release {
            // R8 minify + shrink resources → APK giảm ~30-50% size.
            isMinifyEnabled = true
            isShrinkResources = true
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                file("proguard-rules.pro"),
            )

            // Smart signing: dùng release keystore nếu có, fallback debug.
            val releaseConfig = signingConfigs.getByName("release")
            if (releaseConfig.storeFile != null && releaseConfig.storeFile?.exists() == true) {
                signingConfig = releaseConfig
            } else {
                println("⚠️ [Build] Using DEBUG signing for RELEASE (keystore missing).")
                signingConfig = signingConfigs.getByName("debug")
            }
        }
    }

    // ─── Bundle config (AAB split — Play Store) ─────────────────────
    bundle {
        language { enableSplit = true }
        abi { enableSplit = true }
        density { enableSplit = true }
    }
}

flutter {
    source = "../.."
}

dependencies {
    // 🔥 Firebase BoM — version cho mọi Firebase product, không cần khai version từng cái.
    // https://firebase.google.com/docs/android/learn-more#bom
    implementation(platform("com.google.firebase:firebase-bom:33.7.0"))

    // MultiDex support — Firebase + nhiều plugins dễ vượt 64K method limit.
    implementation("androidx.multidex:multidex:2.0.1")

    // 🔧 Core library desugaring — cho phép java.time và Java 8+ APIs chạy
    // trên Android API < 26. Bắt buộc cho flutter_local_notifications.
    coreLibraryDesugaring("com.android.tools:desugar_jdk_libs:2.1.4")
}

// ----- BEGIN flavorDimensions (autogenerated by flutter_flavorizr) -----
apply { from("flavorizr.gradle.kts") }
// ----- END flavorDimensions (autogenerated by flutter_flavorizr) -----

// ─── Custom build tasks ──────────────────────────────────────────────
// Đổi tên APK/AAB output: `myapp-dev-release-v1.0.0(1).apk`
apply(from = "rename-outputs.gradle.kts")
// Auto mở Finder/Explorer sau khi build APK/AAB Release
apply(from = "open-folder.gradle.kts")
