export default () => ({
  app: {
    env: process.env.NODE_ENV ?? 'development',
    port: parseInt(process.env.PORT ?? '3000', 10),
    appUrl: process.env.APP_URL ?? 'http://localhost:3000',
    webUrl: process.env.WEB_URL ?? 'http://localhost:3001',
    mobileDeeplink: process.env.MOBILE_DEEPLINK ?? 'sportsbooking://',
    corsOrigins: (process.env.CORS_ORIGINS ?? '*').split(','),
  },
  jwt: {
    accessSecret: process.env.JWT_ACCESS_SECRET ?? 'dev-access',
    accessTtl: process.env.JWT_ACCESS_TTL ?? '15m',
    refreshSecret: process.env.JWT_REFRESH_SECRET ?? 'dev-refresh',
    refreshTtl: process.env.JWT_REFRESH_TTL ?? '30d',
  },
  redis: {
    host: process.env.REDIS_HOST ?? 'localhost',
    port: parseInt(process.env.REDIS_PORT ?? '6379', 10),
    password: process.env.REDIS_PASSWORD || undefined,
  },
  mail: {
    host: process.env.MAIL_HOST,
    port: parseInt(process.env.MAIL_PORT ?? '1025', 10),
    user: process.env.MAIL_USER,
    pass: process.env.MAIL_PASS,
    from: process.env.MAIL_FROM ?? 'Sports Booking <no-reply@sportsbooking.local>',
  },
  s3: {
    endpoint: process.env.S3_ENDPOINT,
    region: process.env.S3_REGION ?? 'us-east-1',
    accessKey: process.env.S3_ACCESS_KEY,
    secretKey: process.env.S3_SECRET_KEY,
    bucket: process.env.S3_BUCKET,
    forcePathStyle: process.env.S3_FORCE_PATH_STYLE === 'true',
    publicUrl: process.env.S3_PUBLIC_URL,
  },
  supabase: {
    url: process.env.SUPABASE_URL ?? '',
    key: process.env.SUPABASE_KEY ?? '',
    bucket: process.env.SUPABASE_BUCKET ?? 'sports_booking',
  },
  booking: {
    holdMinutes: parseInt(process.env.BOOKING_HOLD_MINUTES ?? '10', 10),
    paymentTimeoutMinutes: parseInt(process.env.BOOKING_PAYMENT_TIMEOUT_MINUTES ?? '15', 10),
  },
  commission: {
    percent: parseFloat(process.env.PLATFORM_COMMISSION_PERCENT ?? '10'),
  },
  payments: {
    vnpay: {
      tmnCode: process.env.VNPAY_TMN_CODE ?? '',
      hashSecret: process.env.VNPAY_HASH_SECRET ?? '',
      payUrl: process.env.VNPAY_PAY_URL ?? '',
      apiUrl: process.env.VNPAY_API_URL ?? '',
      returnUrl: process.env.VNPAY_RETURN_URL ?? '',
      ipnUrl: process.env.VNPAY_IPN_URL ?? '',
    },
    momo: {
      partnerCode: process.env.MOMO_PARTNER_CODE ?? '',
      accessKey: process.env.MOMO_ACCESS_KEY ?? '',
      secretKey: process.env.MOMO_SECRET_KEY ?? '',
      endpoint: process.env.MOMO_ENDPOINT ?? '',
      queryEndpoint: process.env.MOMO_QUERY_ENDPOINT ?? '',
      refundEndpoint: process.env.MOMO_REFUND_ENDPOINT ?? '',
      returnUrl: process.env.MOMO_RETURN_URL ?? '',
      notifyUrl: process.env.MOMO_NOTIFY_URL ?? '',
    },
    zalopay: {
      appId: process.env.ZALOPAY_APP_ID ?? '',
      key1: process.env.ZALOPAY_KEY1 ?? '',
      key2: process.env.ZALOPAY_KEY2 ?? '',
      createEndpoint: process.env.ZALOPAY_CREATE_ENDPOINT ?? '',
      queryEndpoint: process.env.ZALOPAY_QUERY_ENDPOINT ?? '',
      refundEndpoint: process.env.ZALOPAY_REFUND_ENDPOINT ?? '',
      callbackUrl: process.env.ZALOPAY_CALLBACK_URL ?? '',
      redirectUrl: process.env.ZALOPAY_REDIRECT_URL ?? '',
    },
  },
});
